# -----------------------------
# Server Configuration
# -----------------------------
server:
  base_url: "https://searxng-latest-9f4n.onrender.com"  # change if your Render URL changes
  bind_address: 0.0.0.0
  port: $PORT   # Render provides the port automatically

# -----------------------------
# Logging
# -----------------------------
logging:
  level: info

# -----------------------------
# Default Search Configuration
# -----------------------------
search:
  default_category: general
  safe_search: true

# -----------------------------
# CORS - Allow JS clients to fetch JSON
# -----------------------------
cors:
  allowed_origins:
    - "*"   # allow all domains; for production replace with your website URL

# -----------------------------
# Cache (Free Tier: disable Redis)
# -----------------------------
cache:
  backend: null

# -----------------------------
# Engines (lightweight for free tier)
# -----------------------------
engines:
  google:
    enabled: true
  bing:
    enabled: true
  duckduckgo:
    enabled: true

# -----------------------------
# UI
# -----------------------------
ui:
  theme: oscar

# -----------------------------
# Optional: JSON API works automatically via ?format=json
# -----------------------------
